FROM centos

ARG REPO=release

RUN curl -s https://packagecloud.io/install/repositories/fdio/${REPO}/script.rpm.sh |  bash && \
    yum -y update && \
    yum -y install sudo iproute vpp vpp-plugins vpp-api-python vpp-lib vpp-devel && \
    yum clean all && \
    rm -rf /var/cache/yum
