FROM centos

ARG REPO=release

COPY startvpp1.sh /
COPY startvpp2.sh /
COPY startup1.conf /etc/vpp/startup1.conf
COPY startup2.conf /etc/vpp/startup2.conf
COPY config1.txt /etc/vpp/config1.txt
COPY config2.txt /etc/vpp/config2.txt

RUN curl -s https://packagecloud.io/install/repositories/fdio/${REPO}/script.rpm.sh |  bash
RUN yum -y update; yum -y install sudo iproute vpp vpp-plugins vpp-api-python

