FROM vpp-container-fun/base

COPY startstrongswan.sh /
COPY startvpp.sh /
COPY startup.conf /etc/vpp/startup.conf

RUN yum -y install epel-release && \
    yum -y install strongswan tcpdump && \
    yum clean all && \
    rm -rf /var/cache/yum

ENTRYPOINT /startvpp.sh
